"""add indexes + fix posta_creado_en type

Revision ID: 5e78d32b1624
Revises: 9f0b3a6d7a21
Create Date: 2026-07-18 18:02:09.056804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e78d32b1624'
down_revision: Union[str, Sequence[str], None] = '9f0b3a6d7a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guardia_sustituto_asp_id'), table_name='guardia')
    op.create_index('ix_guardia_fecha_estado', 'guardia', ['fecha', 'estado'], unique=False)
    op.create_index(op.f('ix_guardia_turno_posta_id'), 'guardia', ['turno_posta_id'], unique=False)
    op.drop_constraint(op.f('fk_guardia_sustituto_asp'), 'guardia', type_='foreignkey')
    op.drop_column('guardia', 'sustituto_asp_id')
    op.create_index(op.f('ix_novedad_guardia_id'), 'novedad', ['guardia_id'], unique=False)
    op.create_index(op.f('ix_turno_posta_posta_id'), 'turno_posta', ['posta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turno_posta_posta_id'), table_name='turno_posta')
    op.drop_index(op.f('ix_novedad_guardia_id'), table_name='novedad')
    op.add_column('guardia', sa.Column('sustituto_asp_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_guardia_sustituto_asp'), 'guardia', 'asp', ['sustituto_asp_id'], ['id'])
    op.drop_index(op.f('ix_guardia_turno_posta_id'), table_name='guardia')
    op.drop_index('ix_guardia_fecha_estado', table_name='guardia')
    op.create_index(op.f('ix_guardia_sustituto_asp_id'), 'guardia', ['sustituto_asp_id'], unique=False)
    # ### end Alembic commands ###
