"""estado inicial limpio

Revision ID: 7688404045a5
Revises: 
Create Date: 2026-05-21 18:04:47.426894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7688404045a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('posta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ubicacion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('interior', 'perimetral', 'movil', 'punto_critico', name='tipopostaenum'), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('asp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ci', sa.String(length=11), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.Enum('masculino', 'femenino', name='sexoenum'), nullable=False),
    sa.Column('nivel_escolaridad', sa.Enum('primaria', 'secundaria', 'preuniversitario', 'tecnico_medio', 'universitario', name='escolaridadenum'), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'suspendido', 'baja_temporal', 'baja_definitiva', name='estadoaspenum'), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('cargo_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('LENGTH(ci) = 11', name='ck_asp_ci_length'),
    sa.CheckConstraint('fecha_ingreso >= fecha_nacimiento', name='ck_asp_fechas'),
    sa.ForeignKeyConstraint(['cargo_id'], ['cargo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asp_ci'), 'asp', ['ci'], unique=True)
    op.create_index(op.f('ix_asp_estado'), 'asp', ['estado'], unique=False)
    op.create_table('turno_posta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posta_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('cruza_medianoche', sa.Boolean(), nullable=False),
    sa.Column('asp_requeridos', sa.SmallInteger(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.CheckConstraint('asp_requeridos >= 1', name='ck_turno_asp_requeridos'),
    sa.ForeignKeyConstraint(['posta_id'], ['posta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asp_id', sa.Integer(), nullable=False),
    sa.Column('turno_posta_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio_real', sa.DateTime(), nullable=True),
    sa.Column('hora_fin_real', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.Enum('planificada', 'activa', 'finalizada', 'ausente', 'cancelada', name='estadoguardiaenum'), nullable=False),
    sa.Column('motivo_ausencia', sa.String(length=200), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado != 'ausente' OR motivo_ausencia IS NOT NULL", name='ck_guardia_ausencia_motivo'),
    sa.ForeignKeyConstraint(['asp_id'], ['asp.id'], ),
    sa.ForeignKeyConstraint(['turno_posta_id'], ['turno_posta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asp_id', 'turno_posta_id', 'fecha', name='uq_guardia_asp_turno_fecha')
    )
    op.create_index(op.f('ix_guardia_asp_id'), 'guardia', ['asp_id'], unique=False)
    op.create_index(op.f('ix_guardia_estado'), 'guardia', ['estado'], unique=False)
    op.create_index(op.f('ix_guardia_fecha'), 'guardia', ['fecha'], unique=False)
    op.create_table('novedad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guardia_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo', sa.Enum('incidente', 'comunicado', 'entrega_recepcion', 'solicitud', 'otro', name='tiponovedadenum'), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('severidad', sa.Enum('baja', 'media', 'alta', 'critica', name='severidadenum'), nullable=False),
    sa.ForeignKeyConstraint(['guardia_id'], ['guardia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('novedad')
    op.drop_index(op.f('ix_guardia_fecha'), table_name='guardia')
    op.drop_index(op.f('ix_guardia_estado'), table_name='guardia')
    op.drop_index(op.f('ix_guardia_asp_id'), table_name='guardia')
    op.drop_table('guardia')
    op.drop_table('turno_posta')
    op.drop_index(op.f('ix_asp_estado'), table_name='asp')
    op.drop_index(op.f('ix_asp_ci'), table_name='asp')
    op.drop_table('asp')
    op.drop_table('usuario')
    op.drop_table('posta')
    op.drop_table('cargo')
    # ### end Alembic commands ###
