"""add audit_log table

Revision ID: c247deece2b7
Revises: 5e78d32b1624
Create Date: 2026-08-26 15:56:47.652244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c247deece2b7'
down_revision: Union[str, Sequence[str], None] = '5e78d32b1624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=20), nullable=False),
    sa.Column('datos_anteriores', sa.Text(), nullable=True),
    sa.Column('datos_nuevos', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entidad_fecha', 'audit_log', ['entidad', 'fecha'], unique=False)
    op.create_index(op.f('ix_audit_log_accion'), 'audit_log', ['accion'], unique=False)
    op.create_index(op.f('ix_audit_log_entidad'), 'audit_log', ['entidad'], unique=False)
    op.create_index(op.f('ix_audit_log_entidad_id'), 'audit_log', ['entidad_id'], unique=False)
    op.create_index(op.f('ix_audit_log_fecha'), 'audit_log', ['fecha'], unique=False)
    op.create_index(op.f('ix_audit_log_usuario'), 'audit_log', ['usuario'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_usuario'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_fecha'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entidad_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entidad'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_accion'), table_name='audit_log')
    op.drop_index('ix_audit_entidad_fecha', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
